export type ToolCategory = "image" | "pdf" | "converter" | "developer" | "ai" | "utility";

export type ToolInfo = {
  slug: string;
  name: string;
  category: ToolCategory;
  description: string;
  keyword: string;
  title: string;
  metaDescription: string;
  howToUse: string[];
  benefits: string[];
};

export const categoryLabels: Record<ToolCategory, string> = {
  image: "Image Tools",
  pdf: "PDF Tools",
  converter: "Converter Tools",
  developer: "Developer Tools",
  ai: "AI Tools",
  utility: "Utility Tools",
};

export const categoryRoutes: Record<ToolCategory, string> = {
  image: "/image-tools",
  pdf: "/pdf-tools",
  converter: "/converter-tools",
  developer: "/developer-tools",
  ai: "/ai-tools",
  utility: "/utility-tools",
};

export const tools: ToolInfo[] = [
  {
    slug: "compress-image",
    name: "Image Compressor",
    category: "image",
    description: "Reduce JPG and PNG image size before sharing or uploading.",
    keyword: "image compressor online",
    title: "Free Image Compressor Online",
    metaDescription: "Compress JPG and PNG images online with JaldiBhejo. Reduce image file size quickly in your browser.",
    howToUse: ["Choose a JPG or PNG image.", "Select the compression quality.", "Preview size savings.", "Download the compressed image."],
    benefits: ["Smaller image files", "Faster sharing", "Useful before email uploads", "Browser-based workflow"],
  },
  {
    slug: "jpg-to-png",
    name: "JPG to PNG",
    category: "image",
    description: "Convert JPG photos into PNG images.",
    keyword: "JPG to PNG converter",
    title: "JPG to PNG Converter Online",
    metaDescription: "Convert JPG images to PNG format online with a simple browser tool.",
    howToUse: ["Upload a JPG image.", "Convert it to PNG.", "Download the PNG file."],
    benefits: ["Better transparency support", "Simple format conversion", "No software installation"],
  },
  {
    slug: "png-to-jpg",
    name: "PNG to JPG",
    category: "image",
    description: "Convert PNG images to smaller JPG files.",
    keyword: "PNG to JPG converter",
    title: "PNG to JPG Converter Online",
    metaDescription: "Convert PNG images to JPG online for smaller file sizes and easier sharing.",
    howToUse: ["Select a PNG file.", "Convert it into JPG.", "Download the new JPG image."],
    benefits: ["Smaller output files", "Works well for photos", "Easy sharing"],
  },
  {
    slug: "image-to-pdf",
    name: "Image to PDF",
    category: "image",
    description: "Turn images into a clean PDF document.",
    keyword: "image to PDF converter",
    title: "Image to PDF Converter",
    metaDescription: "Convert JPG and PNG images into a PDF document online.",
    howToUse: ["Upload one or more images.", "Arrange the order.", "Create the PDF.", "Download your document."],
    benefits: ["Great for documents", "Easy mobile sharing", "Organized output"],
  },
  {
    slug: "image-resizer",
    name: "Image Resizer",
    category: "image",
    description: "Resize image width and height for web, forms, and sharing.",
    keyword: "image resizer online",
    title: "Image Resizer Online",
    metaDescription: "Resize images online by width, height, or percentage.",
    howToUse: ["Upload an image.", "Enter new dimensions.", "Resize and download."],
    benefits: ["Fit upload limits", "Prepare website images", "Reduce dimensions quickly"],
  },
  {
    slug: "background-remover",
    name: "Background Remover",
    category: "ai",
    description: "Remove image backgrounds for profile photos and product images.",
    keyword: "background remover",
    title: "Background Remover Online",
    metaDescription: "Remove image backgrounds online for clean profile, product, and social images.",
    howToUse: ["Upload an image.", "Remove the background.", "Preview the cutout.", "Download the result."],
    benefits: ["Cleaner visuals", "Useful for products", "Fast editing workflow"],
  },
  {
    slug: "video-compressor",
    name: "Video Compressor",
    category: "converter",
    description: "Compress large video files locally in your browser.",
    keyword: "video compressor",
    title: "Video Compressor Online",
    metaDescription: "Compress MP4 and video files online directly in your browser without uploading to any server.",
    howToUse: ["Select a video file.", "Click compress.", "Wait for the WebAssembly engine.", "Download the smaller video."],
    benefits: ["No server upload", "Private and secure", "Reduces file size for sharing"],
  },
  {
    slug: "audio-extractor",
    name: "Audio Extractor",
    category: "converter",
    description: "Extract MP3 audio from any video file.",
    keyword: "audio extractor",
    title: "Audio Extractor Online",
    metaDescription: "Extract high-quality MP3 audio from video files locally using WebAssembly.",
    howToUse: ["Upload a video.", "Click extract.", "Download the MP3 file."],
    benefits: ["Fast extraction", "Private processing", "No size limits"],
  },
  {
    slug: "webp-converter",
    name: "WebP Converter",
    category: "converter",
    description: "Convert images into WebP for modern websites.",
    keyword: "WebP converter",
    title: "WebP Converter Online",
    metaDescription: "Convert images to WebP format for faster websites and smaller image files.",
    howToUse: ["Upload an image.", "Convert to WebP.", "Download the optimized image."],
    benefits: ["Better web performance", "Smaller images", "Modern browser support"],
  },
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    category: "pdf",
    description: "Combine multiple PDF files into one document.",
    keyword: "merge PDF online",
    title: "Merge PDF Online",
    metaDescription: "Merge multiple PDF files into one organized document online.",
    howToUse: ["Upload PDF files.", "Arrange them in order.", "Merge into one PDF.", "Download the final file."],
    benefits: ["Organize documents", "Easy sharing", "No desktop software needed"],
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    category: "pdf",
    description: "Extract pages or split one PDF into smaller files.",
    keyword: "split PDF online",
    title: "Split PDF Online",
    metaDescription: "Split PDF files online and extract selected pages quickly.",
    howToUse: ["Upload a PDF.", "Choose pages to extract.", "Split the document.", "Download selected pages."],
    benefits: ["Smaller documents", "Easy page extraction", "Cleaner sharing"],
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    category: "pdf",
    description: "Reduce PDF file size for email and upload limits.",
    keyword: "compress PDF online",
    title: "Compress PDF Online",
    metaDescription: "Compress PDF files online to reduce file size for sharing and uploads.",
    howToUse: ["Upload a PDF.", "Choose compression level.", "Compress the file.", "Download the smaller PDF."],
    benefits: ["Meet upload limits", "Faster email attachments", "Save storage"],
  },
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    category: "pdf",
    description: "Convert PDF documents into editable Word files.",
    keyword: "PDF to Word converter",
    title: "PDF to Word Converter",
    metaDescription: "Convert PDF files to editable Word documents online.",
    howToUse: ["Upload a PDF.", "Convert to Word.", "Download the editable file."],
    benefits: ["Edit document text", "Useful for forms", "Simple conversion"],
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    category: "pdf",
    description: "Convert DOC and DOCX files to PDF.",
    keyword: "Word to PDF converter",
    title: "Word to PDF Converter",
    metaDescription: "Convert Word documents into PDF files online.",
    howToUse: ["Upload a Word file.", "Convert to PDF.", "Download the PDF."],
    benefits: ["Share stable documents", "Preserve formatting", "Professional output"],
  },
  {
    slug: "pdf-to-image",
    name: "PDF to Image",
    category: "pdf",
    description: "Convert PDF pages into image files.",
    keyword: "PDF to image converter",
    title: "PDF to Image Converter",
    metaDescription: "Convert PDF pages into JPG or PNG images online.",
    howToUse: ["Upload a PDF.", "Select output format.", "Convert pages.", "Download images."],
    benefits: ["Preview pages easily", "Share single pages", "Useful for thumbnails"],
  },
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    category: "utility",
    description: "Generate QR codes for links, text, and contact details.",
    keyword: "QR code generator",
    title: "Free QR Code Generator",
    metaDescription: "Create QR codes online for URLs, text, contact details, and quick sharing.",
    howToUse: ["Enter your link or text.", "Generate a QR code.", "Download or share it."],
    benefits: ["Quick mobile sharing", "Printable codes", "Useful for business and events"],
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    category: "utility",
    description: "Create strong random passwords for online accounts.",
    keyword: "password generator",
    title: "Strong Password Generator",
    metaDescription: "Generate strong random passwords online for safer accounts.",
    howToUse: ["Choose password length.", "Select numbers, symbols, and letters.", "Generate and copy the password."],
    benefits: ["Better account security", "Random output", "Fast password creation"],
  },
  {
    slug: "word-counter",
    name: "Word Counter",
    category: "utility",
    description: "Count words, characters, sentences, and reading time.",
    keyword: "word counter online",
    title: "Word Counter Online",
    metaDescription: "Count words and characters online for essays, posts, and documents.",
    howToUse: ["Paste your text.", "View word and character counts.", "Edit and recount instantly."],
    benefits: ["Useful for writing limits", "Fast text analysis", "No signup required"],
  },
  {
    slug: "text-case-converter",
    name: "Text Case Converter",
    category: "utility",
    description: "Convert text into uppercase, lowercase, title case, and sentence case.",
    keyword: "case converter",
    title: "Text Case Converter",
    metaDescription: "Convert text case online to uppercase, lowercase, title case, and sentence case.",
    howToUse: ["Paste your text.", "Choose a case format.", "Copy the converted text."],
    benefits: ["Clean formatting", "Fast editing", "Useful for titles and documents"],
  },
  {
    slug: "regex-tester",
    name: "Regex Tester",
    category: "developer",
    description: "Test regular expressions in real-time with live matching.",
    keyword: "regex tester",
    title: "Regex Tester Online",
    metaDescription: "Test regular expressions online with a live regex tester and debugger.",
    howToUse: ["Enter your regex pattern.", "Set optional flags.", "Type a test string.", "View live matches."],
    benefits: ["Fast debugging", "Developer-friendly", "No account required"],
  },
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    category: "developer",
    description: "Format and validate JSON for easier debugging.",
    keyword: "JSON formatter",
    title: "JSON Formatter and Validator",
    metaDescription: "Format, beautify, and validate JSON data online for development and debugging.",
    howToUse: ["Paste JSON data.", "Click format.", "Review errors or copy clean output."],
    benefits: ["Readable JSON", "Faster debugging", "Useful for APIs"],
  },
  {
    slug: "html-formatter",
    name: "HTML Formatter",
    category: "developer",
    description: "Beautify messy HTML code into readable structure.",
    keyword: "HTML formatter",
    title: "HTML Formatter Online",
    metaDescription: "Format and beautify HTML code online for easier editing.",
    howToUse: ["Paste HTML.", "Format the code.", "Copy the readable output."],
    benefits: ["Cleaner markup", "Faster review", "Better development workflow"],
  },
  {
    slug: "css-formatter",
    name: "CSS Formatter",
    category: "developer",
    description: "Format CSS code for readability.",
    keyword: "CSS formatter",
    title: "CSS Formatter Online",
    metaDescription: "Beautify and format CSS code online.",
    howToUse: ["Paste CSS.", "Click format.", "Copy clean CSS."],
    benefits: ["Readable stylesheets", "Easy debugging", "Cleaner code"],
  },
  {
    slug: "javascript-formatter",
    name: "JavaScript Formatter",
    category: "developer",
    description: "Beautify JavaScript code for debugging and review.",
    keyword: "JavaScript formatter",
    title: "JavaScript Formatter Online",
    metaDescription: "Format and beautify JavaScript code online for easier debugging.",
    howToUse: ["Paste JavaScript.", "Format the code.", "Copy the output."],
    benefits: ["Readable scripts", "Debug faster", "Developer-friendly"],
  },
  {
    slug: "base64-encoder",
    name: "Base64 Encoder",
    category: "developer",
    description: "Encode text into Base64 format.",
    keyword: "Base64 encoder",
    title: "Base64 Encoder Online",
    metaDescription: "Encode text and strings into Base64 format online.",
    howToUse: ["Paste text.", "Encode to Base64.", "Copy the encoded output."],
    benefits: ["Fast encoding", "Useful for developers", "Simple text processing"],
  },
  {
    slug: "base64-decoder",
    name: "Base64 Decoder",
    category: "developer",
    description: "Decode Base64 strings back into readable text.",
    keyword: "Base64 decoder",
    title: "Base64 Decoder Online",
    metaDescription: "Decode Base64 text online into readable strings.",
    howToUse: ["Paste Base64 text.", "Decode it.", "Copy the readable output."],
    benefits: ["Fast decoding", "Useful for API work", "Simple debugging"],
  },
  {
    slug: "url-encoder",
    name: "URL Encoder",
    category: "developer",
    description: "Encode URLs and query strings safely.",
    keyword: "URL encoder",
    title: "URL Encoder Online",
    metaDescription: "Encode URLs and query parameters online.",
    howToUse: ["Paste a URL or string.", "Encode it.", "Copy the result."],
    benefits: ["Safe URL formatting", "Useful for links", "Developer utility"],
  },
  {
    slug: "url-decoder",
    name: "URL Decoder",
    category: "developer",
    description: "Decode encoded URLs into readable text.",
    keyword: "URL decoder",
    title: "URL Decoder Online",
    metaDescription: "Decode encoded URLs and query strings online.",
    howToUse: ["Paste encoded text.", "Decode it.", "Copy the readable result."],
    benefits: ["Readable URLs", "Faster debugging", "Simple conversion"],
  },
  {
    slug: "ai-text-summarizer",
    name: "AI Text Summarizer",
    category: "ai",
    description: "Summarize long text into short, readable points.",
    keyword: "AI text summarizer",
    title: "AI Text Summarizer",
    metaDescription: "Summarize long articles, notes, and paragraphs with an AI text summarizer.",
    howToUse: ["Paste your text.", "Choose summary length.", "Generate a short summary."],
    benefits: ["Save reading time", "Create quick notes", "Useful for students and writers"],
  },
  {
    slug: "ai-title-generator",
    name: "AI Title Generator",
    category: "ai",
    description: "Generate title ideas for blogs, videos, and social posts.",
    keyword: "AI title generator",
    title: "AI Title Generator",
    metaDescription: "Generate catchy title ideas for blog posts, videos, and online content.",
    howToUse: ["Enter your topic.", "Generate title ideas.", "Pick and edit your favorite."],
    benefits: ["Faster brainstorming", "Useful for creators", "More headline options"],
  },
];

export function getTool(slug: string) {
  return tools.find((tool) => tool.slug === slug);
}

export function getToolsByCategory(category: ToolCategory) {
  return tools.filter((tool) => tool.category === category);
}

export function getRelatedTools(tool: ToolInfo, limit = 3) {
  return tools.filter((candidate) => candidate.category === tool.category && candidate.slug !== tool.slug).slice(0, limit);
}
